### ISSUE TITLE
Gmail favicon isn't replaced if unread message icon is used

### ISSUE THREAD

**Issue by CennoxX** [dangeredwolf/classic-google-icons#1]
If the unread count of messages is shown in the favicon of Gmail (Settings > Advanced > Unread message icon) the ugly new icon is shown, instead of the classic.

**Comment by pepper-lees** [comment]
Ah, good catch. I don't have a copy of any of the unread icons, but I can manually make them with After Effects. I hope the 100 tiny images don't take much storage space.

**Comment by dangeredwolf** [comment]
I didn't catch this! I appreciate you telling me about this, I didn't even know that was a thing. I'll figure out what icons I'll need.

**Comment by CennoxX** [comment]
> I hope the 100 tiny images don't take much storage space.

I think it's 29 images: From 0 to 19, then in steps of ten from 20+ to 100+
https://ssl.gstatic.com/ui/v1/icons/mail/rfr/unreadcountfavicon/2/0.png
[...]
https://ssl.gstatic.com/ui/v1/icons/mail/rfr/unreadcountfavicon/2/100+.png

There are also some dynamic solutions (https://github.com/ejci/favico.js) but that might be overkill...

**Comment by pepper-lees** [comment]
Fixed! Dangeredwolf will have to publish the new version to the web stores, but you can add it as an unpacked extension for the time being.

**Comment by dangeredwolf** [comment]
oops I forgot to close this issue after I fixed it, my bad 😅
