### ISSUE TITLE
Calendar icon is not replaced

### ISSUE THREAD

**Issue by vonneudeck** [dangeredwolf/classic-google-icons#2]
Great extension, it gives back accessibility for those with poor eyesight. Thank you for making it.
The version 1.2.0 for firefox does not show the blue icon for google calendar though, but the colourful one.

**Comment by dangeredwolf** [comment]
Thanks for reporting this issue! Yep, Calendar used to work before but at some point Google seems to have broken it. I don't really use Google Calendar so I did not notice it breaking. I'll get this fixed ASAP

**Comment by dangeredwolf** [comment]
Oops sorry, I've been a bit busy with college and stuff lately, but I did get this fixed and I published version 1.3.0 with the change. It'll roll out as the extension stores approve it.

**Comment by vonneudeck** [comment]
Thank you so much. And college always comes before random strangers.
